"""initial migration

Revision ID: 345e52cd52c2
Revises: 
Create Date: 2023-04-25 01:38:10.115494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345e52cd52c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_food', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_food')

    # ### end Alembic commands ###
