"""add adminBoolean

Revision ID: 482ad0cd836e
Revises: c74d75c19475
Create Date: 2023-05-06 15:53:08.140588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482ad0cd836e'
down_revision = 'c74d75c19475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
