"""about_author column

Revision ID: 832aba28fa40
Revises: b5529faf2598
Create Date: 2023-05-02 13:47:50.530988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832aba28fa40'
down_revision = 'b5529faf2598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
