"""change db column from favorite_food to organization

Revision ID: 917ee3d4506c
Revises: 09dcbb1f2131
Create Date: 2023-05-01 02:23:33.766983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '917ee3d4506c'
down_revision = '09dcbb1f2131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', sa.String(length=200), nullable=True))
        batch_op.drop_column('favorite_food')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_food', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('organization')

    # ### end Alembic commands ###
